[features]
seeds = false
[programs.localnet]
shared_ledger = "27b22Rj4yVNXM1vEdh65LJ2HsfbmWwBeoncMEFd14bhL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/medartus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
